#NEC Phone System Information
RECV: 82 # Limit to 82 bytes for incoming information
TS: 5 # Time Sleep
STO: 300 # Socket Time Out when no data recieved
DATA: [POT, POTA, PIN, ALB, BRD, PTRS, IVIN, ICM, IVOT, IVOTP, ITRS, SDTA, IDIN, IDOT] # Data type to look for when reciving from PBX

SERVERS:
  - name: <Any Name>
    host: <IP Address>
    port: <Port>
  - name: <Any Name>
    host: <IP Address>
    port: <Port>

